CREATE TABLE IF NOT EXISTS projects (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 budget REAL NOT NULL,
 status TEXT NOT NULL,
 created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS activities (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 project_id INTEGER NOT NULL,
 name TEXT NOT NULL,
 planned_days INTEGER NOT NULL,
 progress REAL NOT NULL,
 risk_signal REAL NOT NULL,
 delay_days INTEGER NOT NULL,
 delayed INTEGER NOT NULL
);
